// Weblisk — Application Configuration
// Single source of truth for brand, routes, and shell content.

export const app = {
  name: "Weblisk",
  version: "1.0",
  cdn: "https://cdn.weblisk.dev",
  icon: "bolt",
  taglines: ["Zero dependencies", "No build step"],
};

export const routes = [
  {
    path: "/index.html",
    label: "Home",
    icon: "home",
    desc: "Landing page",
  },
  {
    path: "/docs/index.html",
    label: "Docs",
    icon: "book",
    desc: "Documentation",
  },
  {
    path: "/docs/quick-start.html",
    label: "Quick Start",
    icon: "bolt",
    desc: "Get started in under a minute",
  },
  {
    path: "/docs/installation.html",
    label: "Installation",
    icon: "box",
    desc: "Install and scaffold a project",
  },
  {
    path: "/docs/signals.html",
    label: "Signals",
    icon: "refresh",
    desc: "Reactive state primitives",
  },
  {
    path: "/docs/islands.html",
    label: "Islands",
    icon: "layers",
    desc: "Islands architecture",
  },
  {
    path: "/docs/hydration.html",
    label: "Hydration",
    icon: "bolt",
    desc: "Hydration strategies",
  },
  {
    path: "/docs/components.html",
    label: "Components",
    icon: "box",
    desc: "UI components",
  },
  {
    path: "/docs/routing.html",
    label: "Routing",
    icon: "globe",
    desc: "Multi-page navigation",
  },
  {
    path: "/docs/state.html",
    label: "State",
    icon: "layers",
    desc: "State management",
  },
  {
    path: "/docs/security.html",
    label: "Security",
    icon: "shield",
    desc: "CSP, CSRF, sanitization",
  },
  {
    path: "/docs/performance.html",
    label: "Performance",
    icon: "chart",
    desc: "Web vitals and profiling",
  },
  {
    path: "/docs/pwa.html",
    label: "PWA",
    icon: "globe",
    desc: "Progressive Web App support",
  },
  {
    path: "/docs/fetch.html",
    label: "Fetch",
    icon: "globe",
    desc: "HTTP client module",
  },
  {
    path: "/docs/realtime.html",
    label: "Realtime",
    icon: "bolt",
    desc: "WebSocket and SSE",
  },
  {
    path: "/docs/analytics.html",
    label: "Analytics",
    icon: "chart",
    desc: "Privacy-first analytics and A/B testing",
  },
  {
    path: "/docs/workers.html",
    label: "Workers",
    icon: "gear",
    desc: "Web Workers",
  },
  {
    path: "/docs/testing.html",
    label: "Testing",
    icon: "check",
    desc: "Test utilities",
  },
  {
    path: "/docs/cli.html",
    label: "CLI",
    icon: "terminal",
    desc: "Command-line tool",
  },
  {
    path: "/docs/a11y.html",
    label: "Accessibility",
    icon: "eye",
    desc: "ARIA, focus management, reduced motion",
  },
  {
    path: "/docs/store.html",
    label: "Store",
    icon: "layers",
    desc: "Local-first data store",
  },
  {
    path: "/docs/scheduler.html",
    label: "Scheduler",
    icon: "clock",
    desc: "Task scheduling and idle work",
  },
  {
    path: "/docs/transitions.html",
    label: "Transitions",
    icon: "refresh",
    desc: "Page and view transitions",
  },
  {
    path: "/docs/ui.html",
    label: "UI",
    icon: "box",
    desc: "UI utilities and components",
  },
  {
    path: "/docs/integration.html",
    label: "Integration",
    icon: "globe",
    desc: "Third-party integration guide",
  },
  {
    path: "/docs/project-structure.html",
    label: "Project Structure",
    icon: "folder",
    desc: "Recommended file layout",
  },
  {
    path: "/docs/devtools.html",
    label: "DevTools",
    icon: "gear",
    desc: "Debug overlay for islands and signals",
  },
  {
    path: "/dashboard.html",
    label: "Dashboard",
    icon: "chart",
    desc: "Dashboard example",
  },
  {
    path: "/features.html",
    label: "Features",
    icon: "layers",
    desc: "Interactive feature demos",
  },
  {
    path: "/features/networking.html",
    label: "Networking Demos",
    icon: "globe",
    desc: "Fetch, WebSocket, SSE, Transport",
  },
  {
    path: "/features/security.html",
    label: "Security Demos",
    icon: "shield",
    desc: "Sanitize, Trusted Types, CSRF, CSP",
  },
  {
    path: "/features/core.html",
    label: "Core Demos",
    icon: "box",
    desc: "Lazy Islands, Error Boundaries, Workers, Scheduler",
  },
  {
    path: "/features/state.html",
    label: "State Demos",
    icon: "layers",
    desc: "IDB Signals, Cross-Tab Sync, Undo/Redo",
  },
  {
    path: "/features/data.html",
    label: "Data Demos",
    icon: "database",
    desc: "Local-First Store, Sync Status",
  },
  {
    path: "/features/performance.html",
    label: "Performance Demos",
    icon: "chart",
    desc: "User Timing, Core Web Vitals",
  },
  {
    path: "/features/a11y.html",
    label: "Accessibility Demos",
    icon: "eye",
    desc: "ARIA, Focus Trap, Reduced Motion",
  },
  {
    path: "/features/pwa.html",
    label: "PWA Demos",
    icon: "globe",
    desc: "Manifest, Connectivity, Push",
  },
  {
    path: "/features/transitions.html",
    label: "Transitions Demos",
    icon: "refresh",
    desc: "View Transitions, Shared Elements, Transition Types",
  },
  {
    path: "/features/routing.html",
    label: "Routing Demos",
    icon: "arrow",
    desc: "Route Guards, Hash Routing, Navigation API",
  },
  {
    path: "/features/components.html",
    label: "Component Demos",
    icon: "box",
    desc: "Counter, Live Clock, Toggle Switches",
  },
  {
    path: "/features/pro.html",
    label: "Pro Demos",
    icon: "star",
    desc: "Analytics, A/B, Tables, Charts, Auth, CRDTs",
  },
  {
    path: "/settings.html",
    label: "Settings",
    icon: "gear",
    desc: "Settings example",
  },
  {
    path: "/pro.html",
    label: "Pro",
    icon: "star",
    desc: "Premium modules & priority support",
  },
  {
    path: "/server/index.html",
    label: "Server",
    icon: "globe",
    desc: "Server framework specification",
  },
  {
    path: "/server/specification.html",
    label: "Specification",
    icon: "book",
    desc: "Server protocol and API contracts",
  },
  {
    path: "/server/protocols.html",
    label: "Protocols",
    icon: "bolt",
    desc: "Communication protocols",
  },
  {
    path: "/server/implementations.html",
    label: "Implementations",
    icon: "layers",
    desc: "Language-specific server implementations",
  },
  {
    path: "/server/go.html",
    label: "Go Implementation",
    icon: "box",
    desc: "Reference implementation in Go",
  },
  {
    path: "/blueprints/index.html",
    label: "Blueprints",
    icon: "book",
    desc: "Declarative API and workflow specifications",
  },
  {
    path: "/blueprints/catalog.html",
    label: "Blueprint Catalog",
    icon: "layers",
    desc: "Browse available blueprints",
  },
  {
    path: "/blueprints/authoring.html",
    label: "Authoring Blueprints",
    icon: "gear",
    desc: "Create custom blueprints",
  },
  {
    path: "/agents/index.html",
    label: "Agents",
    icon: "bolt",
    desc: "Autonomous server-side services",
  },
  {
    path: "/agents/catalog.html",
    label: "Agent Catalog",
    icon: "layers",
    desc: "Browse available agents",
  },
  {
    path: "/agents/building.html",
    label: "Building Agents",
    icon: "gear",
    desc: "Create custom agents",
  },
  {
    path: "/agents/protocols.html",
    label: "Agent Protocol",
    icon: "shield",
    desc: "Agent communication protocol",
  },
];
